<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sk_bootstrap_slider"
 *
 * Auto generated by Extension Builder 2014-09-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Bootstrap Image Slider #SK',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Soeren Kroell',
	'author_email' => 'hallo@soerenkroell.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.8',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);